[workspace]
members = ["crates/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "bevy_eventlistener"
version = "0.5.0"
edition = "2021"
description = "Event listeners and callbacks for bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_eventlistener"
keywords = ["gamedev", "bevy", "eventlistener", "callbacks"]
categories = ["game-engines", "rendering"]

[dependencies]
bevy_eventlistener_core = { path = "crates/bevy_eventlistener_core", version = "0.5.0" }
bevy_eventlistener_derive = { path = "crates/bevy_eventlistener_derive", version = "0.5.0" }

[dev-dependencies]
# bevy = { version = "0.11", default-features = false, features = [
bevy = { git = "https://github.com/bevyengine/bevy", rev="35073cf7aa9eaf748e167c103921a6764fcedfb1", default-features = false, features = [
    "bevy_winit",
    "x11",
] }
rand = "0.8"
criterion = "0.5"
